# Generated by Django 3.0.8 on 2020-07-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('present', models.BooleanField()),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('isLeader', models.BooleanField()),
                ('isActive', models.BooleanField()),
                ('syncmask', models.SmallIntegerField(default=0)),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Deployment')),
            ],
        ),
    ]
